name: learnrwanda
description: A simple splash screen for LearnRwanda app.

# Flutter SDK version
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # iOS icons

# Asset declarations
flutter:
  assets:
    - assets/learn_rwanda_logo.png # Ensure the logo is in this location
